site_name: NARU Devlog
site_url: https://blog.flynaru.com
site_author: Chanyoung &quot;Lazuward&quot; Park
copyright: Copyright &copy; 2024 Lazuward
theme:
  name: material
  logo: assets/icon.svg
  palette:
    primary: black
  features:
    - content.code.copy
    - content.code.annotate
plugins:
  - search
  - blog:
      blog_dir: .
      post_excerpt: required
      pagination_per_page: 3
      pagination_if_single_page: true
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences